version: '3.6'

services:
  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    command: -notify-sighup nginx-proxy -wait 5s:30s -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    depends_on:
      - nginx-proxy
    restart: always
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-gen-tmpl:/etc/docker-gen/templates:rw
      - nginx-html:/usr/share/nginx/html
      - nginx-htpasswd:/etc/nginx/htpasswd:ro
      - nginx-ssl:/etc/nginx/certs:ro
      - nginx-vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-html:/usr/share/nginx/html
      - nginx-ssl:/etc/nginx/certs:ro
      - nginx-vhost:/etc/nginx/vhost.d
      - ./nginx/conf.d/security.conf:/etc/nginx/conf.d/security.conf
      - ./nginx/conf.d/server.conf:/etc/nginx/conf.d/server.conf
  nginx-ssl:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-ssl
    depends_on:
      - nginx-gen
      - nginx-proxy
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - NGINX_PROXY_CONTAINER=nginx-proxy
    restart: always
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-html:/usr/share/nginx/html
      - nginx-ssl:/etc/nginx/certs:rw
      - nginx-vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  nginx-conf:
  nginx-gen-tmpl:
  nginx-html:
  nginx-htpasswd:
  nginx-ssl:
  nginx-vhost:

networks:
  default:
    external:
      name: nginx-proxy
